100-intel

diff --git a/0x00-hello_world/100-intel b/0x00-hello_world/100-intel
--- a/0x00-hello_world/100-intel
+++ b/0x00-hello_world/100-intel
@@ -1,19 +1,2 @@
 #!/bin/bash
-
-if [ -z "$CFILE" ]; then
-    exit 1
-fi
-
-if [ ! -f "$CFILE" ]; then
-    exit 1
-fi
-
-BASENAME=$(basename "$CFILE" .c)
-
-gcc -S -masm=intel "$CFILE" -o "${BASENAME}.s"
-
-if [ $? -eq 0 ]; then
-    echo "Assembly code generated and saved as ${BASENAME}.s"
-else
-    echo "Error: Failed to generate assembly code."
-fi
+if [ -z "$CFILE" ]; then exit 1; fi; if [ ! -f "$CFILE" ]; then exit 1; fi; BASENAME=$(basename "$CFILE" .c); gcc -S -masm=intel "$CFILE" -o "${BASENAME}.s"; if [ $? -eq 0 ]; then echo "Assembly code generated and saved as ${BASENAME}.s"; else echo "Error: Failed to generate assembly code."; fi
